title: Aaron Shikh
logo: /assets/headshotcircle.png
description: >-
  <strong>M.S. in Statistics</strong><br>
  <em>Python, R, SQL, Machine Learning, Statistical Modeling</em><br><br>
  <a href="/assets/resume.pdf" target="_blank" style="text-decoration:none; font-weight:bold;">ğŸ“„ Resume</a> &nbsp;â€¢&nbsp; 
  <a href="https://github.com/aaronshikh" target="_blank" style="text-decoration:none; font-weight:bold;">ğŸ’» GitHub</a> &nbsp;â€¢&nbsp; 
  <a href="https://linkedin.com/in/aaronshikh" target="_blank" style="text-decoration:none; font-weight:bold;">ğŸ”— LinkedIn</a>


theme: jekyll-theme-minimal
